# /etc/shadowmarket/backend.env
# Secure Environment Variables for Shadow Market Backend
#
# IMPORTANT:
# - Replace ALL placeholder values (YOUR_... / FETCH_FROM_VAULT...) with actual secrets.
# - Fetch secrets from Vault or another secure source. DO NOT hardcode them here long-term.
# - Set correct file permissions: sudo chown root:shadowmarket /etc/shadowmarket/backend.env && sudo chmod 640 /etc/shadowmarket/backend.env

# --- Core Django Settings ---
DJANGO_SETTINGS_MODULE=mymarketplace.settings.prod
DJANGO_SECRET_KEY='FETCH_FROM_VAULT_OR_PASTE_SECURE_KEY_HERE' # Replace! e.g., 'your_long_random_secret_key_for_django_!@#$'
DJANGO_ALLOWED_HOSTS='YOUR_ACTUAL_ONION_ADDRESS.onion' # Replace! Add multiple comma-separated if needed. NO trailing slash.
SITE_ID=1

# --- Database ---
DATABASE_URL='postgres://shadowmarket_user:YOUR_DB_PASSWORD_HERE@127.0.0.1:5432/shadowmarket?sslmode=require' # Replace YOUR_DB_PASSWORD_HERE

# --- Cache (Redis DB 1) ---
REDIS_URL='redis://:YOUR_REDIS_PASSWORD_HERE@127.0.0.1:6379/1' # Replace YOUR_REDIS_PASSWORD_HERE

# --- Celery Broker (Redis DB 0) ---
CELERY_BROKER_URL='redis://:YOUR_REDIS_PASSWORD_HERE@127.0.0.1:6379/0' # Replace YOUR_REDIS_PASSWORD_HERE

# --- Security & Operational ---
AXES_ENABLED=True
MAX_FILE_UPLOAD_SIZE_MB=10 # Example: 10MB limit

# --- GPG ---
GPG_HOME=/opt/shadow_market_app/backend/gpg_home

# --- Vault Configuration (Required if fetching secrets from Vault) ---
VAULT_ADDR='http://YOUR_VAULT_IP_OR_DNS:8200' # Example: http://10.0.0.5:8200 or https://vault.internal.domain
# Choose ONE auth method: Token (less secure for services) OR AppRole (preferred)
# VAULT_TOKEN='YOUR_SERVICE_VAULT_TOKEN_HERE' # Not recommended for production services
VAULT_APPROLE_ROLE_ID='YOUR_APP_ROLE_ID_HERE' # Fetch from Vault
VAULT_APPROLE_SECRET_ID='YOUR_APP_ROLE_SECRET_ID_HERE' # Fetch from Vault (often needs wrapping/secure delivery)
# KV Engine config
VAULT_KV_MOUNT_POINT='secret' # Adjust if your KV engine is mounted differently (e.g., 'kv')
VAULT_SECRET_PATH='shadowmarket/config' # Base path in Vault where secrets like DB creds, keys are stored

# --- Cryptocurrency Node RPC Credentials (Fetch from Vault ideally) ---
MONERO_RPC_URL='http://127.0.0.1:18081/json_rpc' # Assumes local daemon
MONERO_WALLET_RPC_URL='http://127.0.0.1:18082/json_rpc' # Assumes local wallet RPC
MONERO_RPC_USER='YOUR_MONERO_WALLET_RPC_USER' # Replace
MONERO_RPC_PASSWORD='YOUR_MONERO_WALLET_RPC_PASSWORD' # Replace

BITCOIN_RPC_URL='http://127.0.0.1:8332' # Assumes local node
BITCOIN_RPC_USER='YOUR_BITCOIN_RPC_USER' # Replace
BITCOIN_RPC_PASSWORD='YOUR_BITCOIN_RPC_PASSWORD' # Replace
BITCOIN_NETWORK='mainnet' # Or 'testnet' / 'signet'

ETHEREUM_NODE_URL='http://127.0.0.1:8545' # Assumes local node
ETHEREUM_CHAIN_ID=1 # 1=Mainnet, 5=Goerli, 11155111=Sepolia

# --- Gnosis Safe Addresses (Required IF using ETH multi-sig) ---
# GNOSIS_SAFE_FACTORY_ADDRESS='0x...' # Replace with actual deployed address
# GNOSIS_SAFE_SINGLETON_ADDRESS='0x...' # Replace with actual deployed address

# --- Marketplace Specific Settings ---
MARKET_USER_USERNAME='MarketAccount' # Username of the fee/bond account in DB
MARKET_FEE_PERCENTAGE_XMR='4.0'
MARKET_FEE_PERCENTAGE_BTC='4.0'
MARKET_FEE_PERCENTAGE_ETH='4.5'
VENDOR_BOND_XMR='5.0'
VENDOR_BOND_BTC='0.05'
VENDOR_BOND_ETH='1.0'
MONERO_CONFIRMATIONS_NEEDED=10
BITCOIN_CONFIRMATIONS_NEEDED=3
ETHEREUM_CONFIRMATIONS_NEEDED=12
PAYMENT_WAIT_HOURS=4
ORDER_AUTO_FINALIZE_DAYS=14
DISPUTE_WINDOW_DAYS=7
DEADMAN_SWITCH_THRESHOLD_DAYS=30
DEFAULT_SESSION_COOKIE_AGE_SECONDS=900 # 15 minutes
OWNER_SESSION_COOKIE_AGE_SECONDS=3600  # 1 hour
DEFAULT_PGP_AUTH_SESSION_TIMEOUT_MINUTES=15
OWNER_PGP_AUTH_SESSION_TIMEOUT_MINUTES=60

# --- Sentry (Optional - Use Self-Hosted Cautiously) ---
# SENTRY_DSN='YOUR_SELF_HOSTED_SENTRY_DSN'
# SENTRY_TRACES_SAMPLE_RATE=0.05