[pytest]
# Django settings module to use for testing
DJANGO_SETTINGS_MODULE = mymarketplace.settings.dev

# Specify where to find tests
python_files = tests.py test_*.py *_tests.py

# Define directories pytest should search for tests within
# Adjust these paths if your test directories are different
    withdraw
    tests
    adminpanel/tests
    forum/tests
    ledger/tests
    notifications/tests
    store/tests

# Command-line options to add automatically
# -v: verbose output
# -s: show print statements
# --nomigrations: Speed up tests by skipping database migrations (use with care)
# --cov=.: Enable code coverage analysis for the current directory (backend/)
# --cov-report=term-missing: Show coverage report in terminal, highlighting missing lines
# Add other options if needed, one per line or space-separated
# Directories to exclude from test discovery (if any)
# norecursedirs = .* build dist CVS _darcs {arch} *.egg migrations staticfiles

# Filter warnings (optional, uncomment and customize as needed)
# filterwarnings =
#     error
#     ignore::DeprecationWarning