# Generated by Django X.X on YYYY-MM-DD HH:MM
from django.db import migrations
from django.utils.text import slugify

# Define the category structure (matches the refined list above)
# Format: ('Category Name', 'Parent Name or None')
# Parent names MUST match exactly how they are defined earlier in the list.
INITIAL_CATEGORIES = [
    # Top Level
    ('Drugs', None),
    ('Digital Goods', None),
    ('Fraud', None),
    ('Counterfeits', None),
    ('Services', None),
    ('Miscellaneous', None),

    # Drugs Sub-categories
    ('Cannabis', 'Drugs'),
    ('Stimulants', 'Drugs'),
    ('Psychedelics', 'Drugs'),
    ('Opioids', 'Drugs'),
    ('Benzodiazepines', 'Drugs'),
    ('Dissociatives', 'Drugs'),
    ('Prescription (Non-Opioid/Benzo/Stimulant)', 'Drugs'), # Renamed for clarity
    ('Other Drugs', 'Drugs'),

    # Cannabis Sub-sub-categories
    ('Flower', 'Cannabis'),
    ('Concentrates', 'Cannabis'),
    ('Edibles', 'Cannabis'),
    ('Seeds', 'Cannabis'),

    # Stimulants Sub-sub-categories
    ('Cocaine', 'Stimulants'),
    ('Amphetamine (Speed)', 'Stimulants'),
    ('Methamphetamine', 'Stimulants'),
    ('MDMA', 'Stimulants'),
    ('Stimulant Analogues / RC', 'Stimulants'),

    # Psychedelics Sub-sub-categories
    ('LSD', 'Psychedelics'),
    ('Psilocybin Mushrooms', 'Psychedelics'),
    ('DMT', 'Psychedelics'),
    ('Mescaline & Cacti', 'Psychedelics'),
    ('Psychedelic Analogues / RC', 'Psychedelics'),

    # Opioids Sub-sub-categories
    ('Heroin', 'Opioids'),
    ('Oxycodone', 'Opioids'),
    ('Hydromorphone / Dilaudid', 'Opioids'),
    ('Opioid Analogues / RC', 'Opioids'),

    # Benzos Sub-sub-categories
    ('Alprazolam (Xanax)', 'Benzodiazepines'),
    ('Diazepam (Valium)', 'Benzodiazepines'),
    ('Clonazepam (Klonopin)', 'Benzodiazepines'),
    ('Benzo Analogues / RC', 'Benzodiazepines'),

    # Dissociatives Sub-sub-categories
    ('Ketamine', 'Dissociatives'),
    ('Dissociative Analogues / RC', 'Dissociatives'),

    # Prescription Sub-sub-categories
    ('Pain Relief (Non-Opioid)', 'Prescription (Non-Opioid/Benzo/Stimulant)'),
    ('Anxiolytics (Non-Benzo)', 'Prescription (Non-Opioid/Benzo/Stimulant)'),
    ('Nootropics / ADHD Agents', 'Prescription (Non-Opioid/Benzo/Stimulant)'),
    ('Other Prescription', 'Prescription (Non-Opioid/Benzo/Stimulant)'),

    # Digital Goods Sub-categories
    ('Software', 'Digital Goods'),
    ('Guides & Tutorials', 'Digital Goods'),
    ('E-Books & Audiobooks', 'Digital Goods'),
    ('Templates', 'Digital Goods'),
    ('Other Digital', 'Digital Goods'),

    # Fraud Sub-categories
    ('CVV & Cards', 'Fraud'),
    ('Dumps', 'Fraud'),
    ('Accounts & Credentials', 'Fraud'),
    ('Personal Information', 'Fraud'), # Decide if allowed
    ('Other Fraud Related', 'Fraud'),

    # Counterfeits Sub-categories
    ('Apparel & Accessories', 'Counterfeits'),
    ('Electronics', 'Counterfeits'),
    ('Jewelry & Watches', 'Counterfeits'),
    ('Money', 'Counterfeits'), # Decide if allowed

    # Services Sub-categories
    ('Programming & Development', 'Services'),
    ('Graphic Design', 'Services'),
    # ('Hosting & VPN', 'Services'), # Removed based on risk?
    ('Other Services', 'Services'),

    # Miscellaneous Sub-categories
    ('Drug Paraphernalia', 'Miscellaneous'),
    ('Lab Supplies', 'Miscellaneous'),
    ('Other Items', 'Miscellaneous'),
]

def populate_categories(apps, schema_editor):
    """Creates the initial category structure."""
    Category = apps.get_model('store', 'Category')
    created_parents = {} # Cache parent objects

    for name, parent_name in INITIAL_CATEGORIES:
        parent = None
        if parent_name:
            parent = created_parents.get(parent_name)
            if not parent:
                # Attempt to fetch parent if somehow missed (shouldn't happen with order)
                try:
                    parent = Category.objects.get(name=parent_name)
                    created_parents[parent_name] = parent # Add to cache
                except Category.DoesNotExist:
                    print(f"\nWARNING: Parent category '{parent_name}' not found for '{name}'. Skipping.")
                    continue

        category, created = Category.objects.get_or_create(
            name=name,
            defaults={
                'parent': parent,
                'slug': slugify(name) # Auto-generate slug
            }
        )
        if created:
            print(f"Created Category: {name} (Parent: {parent_name or 'None'})")
            # Add to cache if it's potentially a parent itself
            created_parents[name] = category
        else:
            # Update parent if it wasn't set correctly before? Optional.
            # category.parent = parent
            # category.save()
            # Add to cache anyway
            created_parents[name] = category


def remove_categories(apps, schema_editor):
    """Removes the categories created by this migration (optional reverse op)."""
    Category = apps.get_model('store', 'Category')
    names_to_delete = [name for name, _ in INITIAL_CATEGORIES]
    # Delete in reverse order to handle dependencies? Or just delete all matching names.
    Category.objects.filter(name__in=names_to_delete).delete()
    print(f"\nAttempted deletion of {len(names_to_delete)} categories.")


class Migration(migrations.Migration):

    dependencies = [
        # Add dependency on the previous migration in the 'store' app
        # e.g., ('store', '000X_previous_migration_name'),
        ('store', '0001_initial'), # Adjust if you have other migrations
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=remove_categories),
    ]