# backend/store/forms.py
import bleach
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate # For login form
from captcha.fields import CaptchaField

# Local imports
from .models import User, Product, Category, Feedback, SupportTicket, TicketMessage, CURRENCY_CHOICES
from .validators import validate_pgp_public_key, validate_monero_address, validate_bitcoin_address, validate_ethereum_address

# --- Constants ---
ALLOWED_TAGS_DESCRIPTION = ['p', 'br', 'ul', 'ol', 'li', 'strong', 'em', 'b', 'i', 'u', 'h3', 'h4', 'h5'] # Allowed HTML in descriptions
BLEACH_STRIP = True # Strip disallowed tags instead of escaping

# --- Authentication Forms ---

class RegistrationForm(forms.ModelForm):
    """Form for user registration, requiring PGP key."""
    username = forms.CharField(
        max_length=150,
        help_text="Required. 150 characters or fewer. Letters, digits and ./-/_ only.",
        widget=forms.TextInput(attrs={'autocomplete': 'username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        min_length=12, # Enforce minimum length
        help_text="Required. Minimum 12 characters."
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        label="Confirm Password"
    )
    pgp_public_key = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10}),
        label="PGP Public Key",
        validators=[validate_pgp_public_key], # Use the robust validator
        help_text="Required. Your full PGP public key block (including BEGIN/END markers). Used for 2FA and secure communication."
    )
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ['username', 'pgp_public_key'] # Password handled separately

    def clean_username(self):
        username = self.cleaned_data.get('username')
        # Check for existing username (case-insensitive check recommended)
        if User.objects.filter(username__iexact=username).exists():
            raise ValidationError("A user with this username already exists.")
        return username

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise ValidationError("Passwords do not match.")
        return password_confirm

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        # Optionally generate login phrase here? Or in the view after save.
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    """Standard login form with username and password."""
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    captcha = CaptchaField()

    # Note: PGP challenge/response handled in a subsequent step/view, not this initial form.

class PGPChallengeResponseForm(forms.Form):
    """Form for submitting the signed PGP challenge during 2FA."""
    signed_challenge = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 15}),
        label="Signed PGP Challenge",
        help_text="Paste the entire PGP signature block generated by signing the challenge text provided."
    )


# --- Product Forms ---

class ProductForm(forms.ModelForm):
    """Form for creating or editing products by vendors."""
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 10}), required=True)

    # Prices - make optional, validation ensures at least one is set
    price_xmr = forms.DecimalField(max_digits=12, decimal_places=6, required=False, min_value=Decimal('0.0'))
    price_btc = forms.DecimalField(max_digits=14, decimal_places=8, required=False, min_value=Decimal('0.0'))
    price_eth = forms.DecimalField(max_digits=18, decimal_places=9, required=False, min_value=Decimal('0.0'))

    # Accepted Currencies
    accepted_currencies = forms.MultipleChoiceField(
        choices=CURRENCY_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=True,
        help_text="Select all currencies you accept for this product."
    )

    # Shipping Options (Simple JSON input for now)
    # For better UX, use a FormSet or dedicated JS widget
    shipping_options = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 5}),
        required=False,
        help_text='Optional. JSON list of options, e.g., [{"name": "Standard", "price_xmr": "0.1"}, {"name": "Express", "price_xmr": "0.5"}]. Prices here must be in XMR for now (or adapt form/model).'
        # TODO: Adapt shipping option price handling for multi-currency
    )

    class Meta:
        model = Product
        fields = [
            'category', 'name', 'description',
            'price_xmr', 'price_btc', 'price_eth', 'accepted_currencies',
            'quantity', 'ships_from', 'ships_to', 'shipping_options',
            'is_active', 'is_featured',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'size': '60'}),
            'ships_from': forms.TextInput(attrs={'size': '40'}),
            'ships_to': forms.Textarea(attrs={'rows': 3}),
        }

    def clean_description(self):
        """Sanitize description HTML."""
        description = self.cleaned_data.get("description", "")
        # Allow specific Markdown/HTML subset using bleach
        cleaned_description = bleach.clean(description, tags=ALLOWED_TAGS_DESCRIPTION, strip=BLEACH_STRIP)
        return cleaned_description

    def clean_shipping_options(self):
        """Validate JSON format for shipping options."""
        options_json = self.cleaned_data.get('shipping_options')
        if not options_json:
            return [] # Return empty list if blank
        try:
            options_list = json.loads(options_json)
            if not isinstance(options_list, list):
                raise ValidationError("Shipping options must be a JSON list.")
            # Further validation: check if each item is a dict with 'name' and 'price_xmr' (or multi-currency price)
            for item in options_list:
                if not isinstance(item, dict) or 'name' not in item or 'price_xmr' not in item: # TODO: Adapt price key
                     raise ValidationError('Each shipping option must be a JSON object with "name" and "price_xmr" keys.')
                # Validate price format?
                Decimal(item['price_xmr']) # TODO: Adapt price key
            return options_list
        except json.JSONDecodeError:
            raise ValidationError("Invalid JSON format for shipping options.")
        except (ValueError, TypeError) as e:
             raise ValidationError(f"Invalid price format in shipping options: {e}")

    def clean(self):
        """Cross-field validation for prices and accepted currencies."""
        cleaned_data = super().clean()
        accepted = cleaned_data.get('accepted_currencies', [])
        price_xmr = cleaned_data.get('price_xmr')
        price_btc = cleaned_data.get('price_btc')
        price_eth = cleaned_data.get('price_eth')
        is_active = cleaned_data.get('is_active', True) # Assume active if field missing

        if is_active:
            has_price = False
            if 'XMR' in accepted and price_xmr is not None: has_price = True
            if 'BTC' in accepted and price_btc is not None: has_price = True
            if 'ETH' in accepted and price_eth is not None: has_price = True

            if not has_price:
                 raise ValidationError("An active product must have a price set for at least one accepted currency.")

        # Ensure prices are only set if currency is accepted
        if price_xmr is not None and 'XMR' not in accepted:
            self.add_error('price_xmr', "Price set, but XMR is not an accepted currency.")
        if price_btc is not None and 'BTC' not in accepted:
            self.add_error('price_btc', "Price set, but BTC is not an accepted currency.")
        if price_eth is not None and 'ETH' not in accepted:
            self.add_error('price_eth', "Price set, but ETH is not an accepted currency.")

        return cleaned_data


# --- Order Forms ---

class PlaceOrderForm(forms.Form):
    """Form submitted when buyer initiates an order (likely via API call data)."""
    quantity = forms.IntegerField(min_value=1)
    selected_currency = forms.ChoiceField(choices=CURRENCY_CHOICES)
    shipping_option_name = forms.CharField(required=False) # Name of the selected option
    # Shipping address info collected separately or encrypted here?
    # Encrypted PGP blob of shipping info might be passed here if done client-side.
    # encrypted_shipping_blob = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        # Accept product instance to validate choices against it
        self.product = kwargs.pop('product', None)
        super().__init__(*args, **kwargs)

    def clean_selected_currency(self):
        currency = self.cleaned_data.get('selected_currency')
        if self.product and currency not in self.product.accepted_currencies:
            raise ValidationError(f"This product does not accept payments in {currency}.")
        return currency

    def clean_quantity(self):
        quantity = self.cleaned_data.get('quantity')
        if self.product and self.product.quantity > 0 and quantity > self.product.quantity:
            raise ValidationError(f"Only {self.product.quantity} items available in stock.")
        return quantity

    def clean_shipping_option_name(self):
        # Validate selected shipping option against product's options
        name = self.cleaned_data.get('shipping_option_name')
        if self.product and not self.product.is_digital():
            if not name: # Require selection for physical goods
                raise ValidationError("Please select a shipping option.")
            options = self.product.shipping_options or []
            if not any(opt.get('name') == name for opt in options):
                raise ValidationError("Invalid shipping option selected.")
        return name


class ShippingInfoForm(forms.Form):
     """Form to collect cleartext shipping information (to be encrypted by the view)."""
     # Define fields based on required shipping info (name, address, country, etc.)
     recipient_name = forms.CharField(max_length=200)
     street_address = forms.CharField(max_length=255)
     address_line_2 = forms.CharField(max_length=255, required=False)
     city = forms.CharField(max_length=100)
     state_province_region = forms.CharField(max_length=100, required=False)
     postal_code = forms.CharField(max_length=20)
     country = forms.CharField(max_length=100) # Consider using django-countries
     phone_number = forms.CharField(max_length=30, required=False)

     def get_shipping_data_dict(self):
        """Returns cleaned data as a dictionary for easy serialization/encryption."""
        if self.is_valid():
            return self.cleaned_data
        return None


class FeedbackForm(forms.ModelForm):
    """Form for submitting feedback on a completed order."""
    rating = forms.ChoiceField(
        choices=[(i, f"{i} Star{'s' if i > 1 else ''}") for i in range(5, 0, -1)], # 5 to 1 stars
        widget=forms.RadioSelect,
        required=True
    )
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 5}),
        required=False, # Allow rating without comment
        max_length=2000
    )

    class Meta:
        model = Feedback
        fields = ['rating', 'comment']


# --- Withdrawal Form ---

class WithdrawalRequestForm(forms.Form):
    """Form to initiate a withdrawal request."""
    currency = forms.ChoiceField(choices=CURRENCY_CHOICES, required=True)
    amount = forms.DecimalField(required=True, min_value=Decimal('0.0')) # Min amount depends on currency/fees
    destination_address = forms.CharField(widget=forms.TextInput(attrs={'size': '60'}), required=True)
    # PGP Signed Confirmation
    pgp_signed_message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 15}),
        label="PGP Signed Confirmation",
        help_text="Sign the exact confirmation message provided (containing amount, address, nonce) with your PGP key."
    )

    def __init__(self, *args, **kwargs):
        # User needed for balance checks? Currency limits?
        # self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_destination_address(self):
        """Validate address based on selected currency."""
        address = self.cleaned_data.get('destination_address')
        currency = self.cleaned_data.get('currency')
        if not address or not currency:
            # Validation depends on currency being selected first
            return address # Let other validation catch missing fields

        try:
            if currency == 'XMR': validate_monero_address(address)
            elif currency == 'BTC': validate_bitcoin_address(address)
            elif currency == 'ETH': validate_ethereum_address(address)
        except ValidationError as e:
            # Add error specifically to this field
            self.add_error('destination_address', e)
        return address

    def clean_amount(self):
        """Validate withdrawal amount against minimums/user balance."""
        amount = self.cleaned_data.get('amount')
        currency = self.cleaned_data.get('currency')
        # TODO: Add checks for minimum withdrawal amount per currency
        # TODO: Add check against user's available balance (requires user object)
        # if self.user and amount > get_user_balance(self.user, currency):
        #     raise ValidationError("Insufficient balance.")
        return amount

    # PGP signature verification happens in the view using the pgp_service


# --- Support Ticket Forms ---

class SupportTicketForm(forms.ModelForm):
    """Form to create a new support ticket."""
    subject = forms.CharField(max_length=255)
    message_body = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10}),
        label="Your Message",
        help_text="Your message will be PGP encrypted for support staff."
    )
    # Optionally link to an order if relevant
    related_order_id = forms.UUIDField(required=False, label="Related Order ID (Optional)")

    class Meta:
        model = SupportTicket
        fields = ['subject'] # Other fields set in view


class TicketMessageForm(forms.Form):
    """Form to reply to an existing support ticket."""
    message_body = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10}),
        label="Your Reply",
        help_text="Your message will be PGP encrypted for the recipient."
    )